#!/usr/bin/env bash

set -e
set -E
set -u
set -o pipefail

declare -r ref="${GITHUB_REF#refs/tags/}"
declare -r log="docs/changelogs/${ref}.md"
declare -r title="$(head -n 1 "${log}")"

gh release create "${ref}" \
  --title "${title### }" \
  --notes "$(tail -n +3 "${log}")"
