#!/usr/bin/env bash

set -e
set -E
set -u
set -o pipefail

declare -r ref="${GITHUB_REF#refs/tags/}"
declare -r ldflags="-X main.Version=${ref} -X main.GitCommit=${GITHUB_SHA:0:8}"
declare ext=""

if [[ $GOOS == "windows" ]]
then
	ext=".exe"
fi

go build -ldflags="${ldflags}"
tar --verbose --create --xz --file "templatefile-${ref}-${GOOS}-${GOARCH}.tar.xz" "templatefile${ext}"
