#!/usr/bin/env bash

set -e
set -E
set -u
set -o pipefail

declare -r ref="${GITHUB_REF#refs/tags/}"
declare -r -x XZ_OP="-9"

gh release upload --clobber "${ref}" "templatefile-${ref}-${GOOS}-${GOARCH}.tar.xz"
